services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  task-service:
    build: .
    container_name: task_service
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification-service:
    build: ../notification_service
    container_name: notification_service
    depends_on:
      rabbitmq:
        condition: service_healthy